# Generated by Django 2.0.7 on 2019-02-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapp',
            name='summary',
            field=models.TextField(default='this is cool!'),
        ),
    ]
